# Generated by Django 4.2.1 on 2023-06-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedEmailDomains',
            fields=[
                ('domain', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'blocked_email_domains',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.IntegerField(primary_key=True, serialize=False)),
                ('company', models.TextField()),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('location', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.TextField(blank=True, null=True)),
                ('scraping_date', models.DateField()),
                ('sort_id', models.IntegerField(blank=True, null=True)),
                ('privilege', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jobs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(max_length=100, unique=True)),
                ('location', models.TextField(max_length=50)),
                ('level', models.TextField(max_length=50)),
                ('remote', models.BooleanField()),
                ('privilege', models.BooleanField(default=False)),
                ('verification_code', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
